name: .NET Build & Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    # everything below runs in the Project-FREAK subfolder
    defaults:
      run:
        working-directory: Project-FREAK

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Project-FREAK.sln

      - name: Build
        run: dotnet build Project-FREAK.sln --no-restore

      - name: Test
        run: dotnet test Project-FREAK.sln --no-build --verbosity normal
