# .github/workflows/dotnet.yml
name: .NET Build & Test

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

jobs:
  build:
    runs-on: windows-latest    # Windows is mandatory for WPF

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore (all TFMs)
        run: dotnet restore "Project-FREAK.sln"

      - name: Build (Windows + plain)
        run: dotnet build   "Project-FREAK.sln" --no-restore --configuration Debug

      - name: Test
        run: dotnet test    "Project-FREAK.sln" --no-build --verbosity normal
