name: .NET Build & Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest     # <--- Must be Windows for WPF bits
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore all
      run: dotnet restore "Project-FREAK.sln"

    - name: Build all
      run: dotnet build   "Project-FREAK.sln" --no-restore --configuration Debug

    - name: Test all
      run: dotnet test    "Project-FREAK.sln" --no-build --verbosity normal
