name: .NET Build & Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./Project-FREAK/Project-FREAK.sln

      - name: Build
        run: dotnet build  ./Project-FREAK/Project-FREAK.sln --no-restore

      - name: Test
        run: dotnet test   ./Project-FREAK/Project-FREAK.sln --no-build --verbosity normal
